Compose: Compose
Raw: Raw Command
Password: Password
Folders: Folders
Login: Login
Logout: Logout
Date: Date
Num: Num
Subject: Subject
Body: Body
Authors: Authors
Attach: Attachments
Tags: Tags
RawWarning: Warning - notmuch is prepended to the command and then the command is passed to the shell!
RunCmd: Run Command
ExitCode: Exit Code
StdOut: Standard Output
StdErr: Standard Error
Send: Send
ExtraHeader: Extra Email Headers
Sent: Message Sent
InPager folder@Text: #{folder} in Pager
ViewInPager: View search results in pager
CheckNew: Check New
MessageRetagging: Message Retagging
SepTagsBySpace: Specify tags separated by spaces
Close: Close
Retag: Retag
TagsToAdd: Tags to add
TagsToRemove: Tags to remove
BodyFormat: Interpret body as
Preview: Preview Html
AddrBookType: Address Book Type
NoAddressBook: No address book
Abook: Abook on server
Google: Google Contacts
GoogleAuth: Authorize Google Contacts
AddrHelpTitle: Entering Email Addresses
AddrHelp: Email addresses should either be entered directly or can be entered as "Name <email@example.com>" without the quotes.  To save the email address and start entering a new one, you can press comma.  Double clicking on an existing entry will allow you to edit it.
