Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000 # can be overridden via the PORT environment variable or --port command line argument

  # AGPLv3 requires a link to the source code on every page.  If you have not changed the
  # source, you can leave it linked to my bitbucket page.
  source-link: https://github.com/afcady/notmuch-web

  # The folders are the notmuch searches that are linked from the navigation bar.
  # The first folder is displayed on the home page.
  folders:
      - name: Inbox
        search: tag:inbox
      - name: Unread
        search: tag:unread
      - name: Lists
        search: tag:lists and tag:unread

  # The retag buttons which appear for threads and messages.  The icon name is from
  # the bootstrap glyphicons-halflings (http://twbs.github.io/bootstrap/2.3.2/base-css.html#icons)
  retag:
      - name: Mark Read
        icon: icon-ok
        remove: ["unread"]

      - name: Archive
        icon: icon-briefcase
        remove: ["unread", "inbox"]

      - name: Kill Thread
        icon: icon-thumbs-down
        add: ["killed"]
        remove: ["unread", "inbox"]

  # List of one or more from addresses for compose.  Format should be  Name <abc@example.com>
  from-addresses:
      - "Name <abc@example.com>"
      - "Name <abc@other.example.com>"

  # List of paths to binaries/scripts to send email.  If no setting is given, /usr/sbin/sendmail
  # is used.  If more than one binary is given, the compose form allows you to choose.  These binaries
  # will be called with the "-t" command line argument and passed the message on standard input.

  #sendmail:
  #    - /usr/local/bin/mysendmail
  #    - /usr/local/bin/anothersendmail


  # The domain for Message-IDs generated by the compose form.  If this setting
  # is missing, the FQDN is looked up

  #message-id-domain: example.com


  # Google Contact Support 
  #
  # The address fields (To, CC, BCC) on the compose form can optionally search
  # contacts either from abook locally or can search from your google contacts.
  # To enable google contacts, you must visit
  # https://code.google.com/apis/console/ click on "API Access", click on
  # "Create an OAuth Client ID", and fill in the data.  The application type
  # must be "Web application" since the contacts will be loaded directly by
  # javascript running in the browser.  The site/hostname must match where you
  # serve notmuch-web from because of CORS protection
  # (http://en.wikipedia.org/wiki/Cross-origin_resource_sharing).  The Redirect
  # URIs can be ignored since we will access google only via javascript. The
  # Client ID can then be copied into the following setting.  Alternatively, an
  # environment variable NOTMUCH_WEB_GOOGLE_CLIENTID will also be searched
  # during startup for the client ID (useful for development).

  #google-client-id: ""


Production:
  # The approot is the full URL to root of notmuch web.
  approot: "http://localhost:3000"

  # You may set a hashed password. If you do not specify this field, PAM
  # authentication will be used instead.
  #
  # See http://hackage.haskell.org/packages/archive/pwstore-fast/latest/doc/html/Crypto-PasswordStore.html
  # for the format. You can generate the password via
  #
  # $ path/to/notmuch-web --make-password
  #
  # hashed-password: "x"

  # The sent box is the folder where sent messages are saved for future indexing by notmuch new. If
  # the setting is missing, the sent messages are not saved.

  #sent-box: /path/to/notmuch/sent
  
  <<: *defaults

Development:
  approot: "http://localhost:3000"
  # For development and testing, the password is hunter2
  hashed-password: "sha256|12|lMzlNz0XK9eiPIYPY96QCQ==|1ZJ/R3qLEF0oCBVNtvNKLwZLpXPM7bLEy/Nc6QBxWro="
  sent-box: sent
  <<: *defaults

Testing:
  approot: "http://localhost:3000"
  # For development and testing, the password is hunter2
  hashed-password: "sha256|12|lMzlNz0XK9eiPIYPY96QCQ==|1ZJ/R3qLEF0oCBVNtvNKLwZLpXPM7bLEy/Nc6QBxWro="
  sent-box: sent
  <<: *defaults

Staging:
  approot: "http://localhost:3000"
  <<: *defaults
